
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching'
import { clientsClaim } from 'workbox-core'

// --- 1. Standard PWA Update Logic ---
// Automatically clean up old caches
cleanupOutdatedCaches()

// Precache assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)

// Take control immediately
self.skipWaiting()
clientsClaim()

// Listener to trigger skipWaiting from UI if needed (though we call it above automatically for simpler updates, 
// strictly speaking for 'prompt' strategy we might wait, but clientsClaim helps take over).
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
})

// --- 2. Push Notification Logic (Migrated from public/sw.js) ---
self.addEventListener('push', function(event) {
  if (event.data) {
    let data;
    try {
        data = event.data.json();
    } catch(e) {
        console.error('Push data parse error', e);
        return;
    }

    const options = {
      body: data.body,
      icon: 'https://cdn-icons-png.flaticon.com/512/993/993891.png',
      badge: 'https://cdn-icons-png.flaticon.com/512/993/993891.png',
      data: {
        url: data.url || '/'
      }
    };

    event.waitUntil(
      self.registration.showNotification(data.title, options)
    );
  }
});

self.addEventListener('notificationclick', function(event) {
  event.notification.close();
  event.waitUntil(
    clients.openWindow(event.notification.data.url)
  );
});
